name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
runs:
  # define the node environment for javascript code
  using: 'node16'
  # references to js files
  # pre: 'setup.js' # if setup needed
  main: 'main.js'
  # post: 'cleanup.js' # if cleanup needed
