name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
inputs:
  bucket:
    description: 'S3 bucket name'
    required: true
  bucket-region:
    description: 'Region of the S3 bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'Folder containing the deployable files'
    required: true
outputs:
  # register an output that is set from inside the js file
  website-url:
    description: 'URL of the website'
runs:
  # define the node environment for javascript code
  using: 'node16'
  # references to js files
  # pre: 'setup.js' # if setup needed
  main: 'main.js'
  # post: 'cleanup.js' # if cleanup needed
